add upvote endpoint and visible endpoint
project-zusammen/hidden-gem-backend pull request #10
Opened 2024-01-04 12:56 UTC by hfzfdlh

- adding endpoint to receive boolean input for upvote and downvote
- adding endpoint to receive boolean input for visibility
- add DTO for upvote input and visible input

2024-01-05 12:36 UTC, fatjan commented on app/main/controller/review_controller.py
> +        """Give visibility status"""
`Give` should be `Update`

2024-01-05 12:37 UTC, fatjan commented on app/main/util/dto.py
> +            "upvote": fields.Boolean(description="upvote")
can we please make this field as required?

the `visible` field as well

2024-01-05 12:39 UTC, fatjan commented on app/main/util/dto.py
> +            "upvote": fields.Boolean(description="upvote")
my bad, it's not required because we have a default value in the `upvote_review` and `update_visibility` methods in review service.
No need to change this to required.

2024-01-05 12:40 UTC, fatjan requested changes
Please add related tests in `test_review_controller.py`

2024-01-06 03:36 UTC, hfzfdlh commented on app/main/controller/review_controller.py
> +        """Give visibility status"""
Give has been replaced to Update on the new push

2024-01-07 02:29 UTC, fatjan commented on tests/controller/test_review_controller.py
> +        self.assertEqual(expected_response.get("upvotes"), res.get("upvote"))
when reviewing this test I realized that the assert isn't correct.

You see that expected_response data is:
```
{'status': 'success', 'message': 'Successfully updated.', 'data': {'title': 'Test Review', 'content': 'This is a test review.', 'location': 'Test Location', 'public_id': 'test-public_id'}
```

and the res is:
```
{'status': 'success', 'message': 'Successfully updated.', 'data': {'title': 'Test Review', 'content': 'This is a test review.', 'location': 'Test Location', 'public_id': 'test-public_id'}
```

In this situation when you assert:
 `self.assertEqual(expected_response.get("upvotes"), res.get("upvote"))`
 it will pass because both are `None`.
 
 Do you get what I mean?

2024-01-07 02:30 UTC, fatjan commented on tests/controller/test_review_controller.py
> +        self.assertEqual(expected_response.get("upvotes"), res.get("upvote"))
My added commit should fix the test, please see and learn why your test was incorrect.
My apology because I did similar thing before.

2024-01-07 02:34 UTC, fatjan commented on tests/controller/test_review_controller.py
> +        mock_visibility_review.return_value = expected_response
Please give a line break here

I've already added it in my commit

2024-01-07 02:35 UTC, fatjan approved these changes
Please check the commit that I added to fix the tests.
Also some other comments as well.

Well done on the PR.

2024-01-08 06:46 UTC, hfzfdlh commented on tests/controller/test_review_controller.py
> +        mock_visibility_review.return_value = expected_response
ok, I'll read your recent commit later on.
just want to make sure is there any other revision that i need to do?

2024-01-09 00:20 UTC, fatjan commented on tests/controller/test_review_controller.py
> +        mock_visibility_review.return_value = expected_response
no, you can resolve conversations and merge this

2024-01-09 13:14 UTC, merged