Feat/user authentication
project-zusammen/hidden-gem-backend pull request #13
Opened 2024-01-12 16:18 UTC by AchmadQiz

- add endpoint for login
- user authentication to secure endpoints
- update the unit test for user endpoint after authentication

2024-01-13 07:19 UTC, fatjan commented on app/main/controller/user_controller.py
> +
can we please remove this line break?

2024-01-13 07:22 UTC, fatjan commented on app/main/controller/user_controller.py
> +    def get(self, decoded_token, public_id):
why do we need to have the `decoded_token, public_id` as arguments in the get method?

2024-01-13 07:24 UTC, fatjan commented on app/main/model/user.py
>              user = self.query.filter_by(public_id=public_id).first()
You have this same exact query in the `check_user_authorization(public_id, user_id)`

I think it's redundant

2024-01-13 07:28 UTC, fatjan commented on app/main/util/helper.py
> +    token = jwt.encode({
can we please format this file?

2024-01-13 07:29 UTC, fatjan commented on app/main/util/token_verify.py
> +            # decoding the payload to fetch the stored details
please remove this unnecessary comment

2024-01-13 07:31 UTC, fatjan commented on tests/model/test_user_model.py
> +        # ASSERT
please add a line break between result and # ASSERT

2024-01-13 07:31 UTC, fatjan requested changes
Kindly update as suggested, thank you.

2024-01-13 08:08 UTC, AchmadQiz commented on app/main/util/helper.py
> +    token = jwt.encode({
I'm still not clear enough, what kind of format is meant?

2024-01-13 08:16 UTC, AchmadQiz commented on app/main/controller/user_controller.py
> +    def get(self, decoded_token, public_id):
For the get user endpoint, should users only be able to view their own profiles or can they also view other people's profiles? Currently, users can only view their own profiles. Also, it's true that the public id can be obtained from the token without having to be used as a arguments.

2024-01-13 08:20 UTC, fatjan commented on app/main/util/helper.py
> +    token = jwt.encode({
https://www.freecodecamp.org/news/auto-format-your-python-code-with-black/

2024-01-13 08:21 UTC, fatjan commented on app/main/controller/user_controller.py
> +    def get(self, decoded_token, public_id):
Let's keep the profile view restricted to the profile's owner only like what you currently do now.
What do you think @fahmirzldi ? Do you agree with this?

2024-01-14 02:23 UTC, AchmadQiz commented on app/main/controller/user_controller.py
> +    def get(self, decoded_token, public_id):
it seems the route definition @ns.route("/user/<public_id>") specifies that the public_id parameter should be part of the route, and Flask-RESTx expects it to be passed as an argument to the corresponding method

2024-01-15 03:02 UTC, AchmadQiz commented
I have pushed the update, please kindly review it

2024-01-17 02:48 UTC, fatjan commented on app/main/model/user.py
>              user = self.query.filter_by(public_id=public_id).first()
since you already have this query:
self.query.filter_by(public_id=public_id).first()

in the `check_user_authorization(public_id, user_id)`

you can remove that and just call check_user_authorization directly to remove redundancy @AchmadQiz

2024-01-17 05:15 UTC, fatjan approved these changes

2024-01-17 05:39 UTC, merged