bookmark endpoint
project-zusammen/hidden-gem-backend pull request #14
Opened 2024-01-16 03:33 UTC by AchmadQiz

- Add create bookmark endpoint. require login first
- Add get bookmark endpoint. this endpoint will automatically extract user public id from token. therefore this endpoint will retrieve the list of bookmark own by user. require login first
- Add delete bookmark. this endpoint is to remove a review from user bookmark

2024-01-17 02:50 UTC, fatjan commented on app/main/model/bookmark.py
> +    def delete_bookmark(self, public_id, user_id):
can we change the `public_id` argument to `bookmark_id` instead?

2024-01-17 02:51 UTC, fatjan commented on app/main/model/bookmark.py
> +            id = (
I think this query is unnecessary

can't we just get bookmark by `bookmark_id` and then check if the `user_id` in the selected bookmark matches the `user_id`

what do you think?

2024-01-17 02:52 UTC, fatjan commented on app/main/model/bookmark.py
> +            id = (
`.join(Bookmark, Bookmark.user_id == User.public_id)`
 
 I think in the db, the `Bookmark.user_id` should be `User.id` not `User.public_id`

2024-01-17 02:53 UTC, fatjan commented on app/main/model/bookmark.py
> +            bookmark = self.query.filter_by(public_id=public_id).first()
This should be done at the beginning before making sure that the selected bookmark belongs to the user who sent the request

2024-01-27 09:53 UTC, fatjan commented
please resolve conflict, thank you

2024-01-27 09:56 UTC, fatjan commented on app/main/model/review.py
> +    def get_review_id_by_public_id(self, public_id):
please do not serialize the whole data if you just need the id.
Here's an example:
![Screenshot 2024-01-27 at 16 55 06](https://github.com/project-zusammen/hidden-gem-backend/assets/46950501/a0bbad97-0e0f-4ac2-9960-e9e56bfc064a)


You just need to make it the other way around, use `public_id` as argument and return the `id (db id)`

2024-01-27 10:43 UTC, AchmadQiz commented
I have pushed the update, please kindly review it

2024-01-29 00:15 UTC, fatjan commented on app/main/model/review.py
> +            review = self.query.filter_by(public_id=public_id).first()
I think you need to filter it by `visible=True` as well, just to make sure.

2024-01-29 00:17 UTC, fatjan requested changes
LGTM, could you please format all your files using black?
Thank you

2024-01-29 23:57 UTC, fatjan commented on app/main/model/bookmark.py
> +            "user_id": self.user_id,
Please convert db user_id to public_id

make the method in user model and only return public user_id here.

Thank you

2024-01-30 00:00 UTC, fatjan commented on app/main/controller/bookmark_controller.py
> +from ..util.dto import BookmarkDto
I think this is unnecessary since you didn't use it anywhere on the code, right?

you can also remove it from `..util.dto`

2024-01-30 00:01 UTC, fatjan requested changes
Please update as per suggestion, thank you

2024-01-30 17:09 UTC, AchmadQiz commented on app/main/controller/bookmark_controller.py
> +from ..util.dto import BookmarkDto
Don't we need it to obtain the review_id input when creating a bookmark?

2024-01-30 17:13 UTC, AchmadQiz commented on app/main/model/bookmark.py
> +            "user_id": self.user_id,
We just need to change the return of user_id to public_id without having to alter the relationship in the bookmark and user tables, right?

2024-02-03 08:32 UTC, fatjan commented on app/main/model/bookmark.py
> +            "user_id": self.user_id,
correct

2024-02-03 08:38 UTC, fatjan commented on app/main/controller/bookmark_controller.py
> +from ..util.dto import BookmarkDto
Which one did I say unnecessary? I forgot :/

2024-02-03 08:39 UTC, fatjan commented on app/main/controller/bookmark_controller.py
> +from ..util.dto import BookmarkDto
ooo, ok.
Yeah I think so.

2024-02-03 16:56 UTC, AchmadQiz commented
I have pushed the update, please kindly review it

2024-02-06 20:58 UTC, fahmirzldi commented on app/main/model/bookmark.py
> +    def delete_bookmark(self, bookmark_id, user_id):
when review got deleted, will the bookmark also got deleted?

2024-02-07 01:36 UTC, fatjan commented on app/main/model/bookmark.py
> +    def delete_bookmark(self, bookmark_id, user_id):
I think it's fine not to delete the bookmark when a review is deleted because we do a soft delete for review, so the data is still in the db, it's just not visible anymore.

2024-02-07 01:38 UTC, fatjan commented on app/main/model/bookmark.py
> +    def delete_bookmark(self, bookmark_id, user_id):
yes it needs to be deleted

2024-02-07 01:52 UTC, fatjan commented on app/main/model/bookmark.py
> +    def delete_bookmark(self, bookmark_id, user_id):
or we can leave it as is and handle it on the FE, when a user is trying to access a review from their bookmark where the review has been removed, there will be a toast that says the review is no longer available

2024-02-25 00:43 UTC, fatjan approved these changes

2024-02-25 01:25 UTC, merged