Feat/region model
project-zusammen/hidden-gem-backend pull request #17
Opened 2024-01-20 05:10 UTC by hfzfdlh

- add more functionality in model/region.py
- create region_controller.py
- create region_service.py

2024-01-20 12:33 UTC, fatjan commented on app/main/model/region.py
> +    # def __init__(self, public_id, city, created_at, updated_at):
should this commented lines be removed?

2024-01-20 12:36 UTC, fatjan commented on app/main/model/region.py
> +        return f"<Region(name={self.city})>"
I think this should be:
```return f"<Region(city ={self.city})>"```

2024-01-20 12:49 UTC, fatjan requested changes
well done on the PR, just had some small comments. Once you've resolved them, kindly let me know.

2024-01-21 11:12 UTC, hfzfdlh commented on app/main/model/region.py
> +    # def __init__(self, public_id, city, created_at, updated_at):
i was thinking that there will be a use for those lines of code, but i will delete it for now

2024-01-21 11:14 UTC, hfzfdlh commented on app/main/model/region.py
> +        return f"<Region(name={self.city})>"
ok, correction on the way

2024-01-21 23:16 UTC, fatjan approved these changes

2024-01-22 04:24 UTC, merged