Feat/pagination on get all review
project-zusammen/hidden-gem-backend pull request #19
Opened 2024-01-23 04:30 UTC by AchmadQiz

Add pagination on get all review endpoint, limit set to 50.

2024-01-23 05:01 UTC, fatjan commented on app/main/controller/review_controller.py
> +        page = request.args.get('page', default=0, type=int)
can you get the page from ns params instead?

2024-01-23 05:09 UTC, fatjan commented on app/main/controller/review_controller.py
> +        page = request.args.get('page', default=0, type=int)
https://flask-restx.readthedocs.io/en/latest/_modules/flask_restx/namespace.html#Namespace

![Screenshot 2024-01-23 at 12 09 04](https://github.com/project-zusammen/hidden-gem-backend/assets/46950501/b5d03ffa-c7cf-450d-838b-72036c66e1da)

2024-01-23 05:11 UTC, fatjan commented on app/main/model/review.py
> +            reviews = self.query.limit(limit).offset(offset).all()
you need to also make sure that it is filtered by `visible=True` like in line 55

The returned reviews should only be those which are visible.

2024-01-23 05:11 UTC, fatjan requested changes
Kindly adjust as suggested in the comments

2024-01-23 05:15 UTC, fatjan commented on tests/model/test_user_model.py
> +        result = user_model.user_auth(token_payload)
Can you please update the following error notification in `user_model.user_auth()`

![Screenshot 2024-01-23 at 12 13 44](https://github.com/project-zusammen/hidden-gem-backend/assets/46950501/64f307e0-1fa4-44cd-9d43-0ad0546f26be)

Line 156 and 162 should be:
"Invalid email/password" to prevent brute-force action

2024-01-23 05:17 UTC, fatjan commented on app/main/controller/review_controller.py
> +    @ns.doc(params={'page': {'description': 'Page number', 'type': 'integer'}})
the fields should be:
`page`: page number
`count`: number of items in each page (max. or default value to 50)

2024-01-23 05:21 UTC, fatjan commented on app/main/controller/review_controller.py
> +    @ns.doc(params={'page': {'description': 'Page number', 'type': 'integer'}})
You need to also add other 3 fields as described in the API contract:
https://docs.google.com/document/d/1YdXuNUR40BospbRPdcEWINZyOrAX-VK4dAUCGTUa6FA/edit?usp=sharing

2024-01-24 11:21 UTC, fahmirzldi commented on app/main/controller/review_controller.py
>  review_dto = ReviewDto()
*test_comment

2024-01-24 11:24 UTC, fahmirzldi commented on app/main/controller/review_controller.py
>  review_dto = ReviewDto()
*test_request

2024-01-25 03:31 UTC, AchmadQiz commented on app/main/controller/review_controller.py
> +        page = request.args.get('page', default=0, type=int)
it seems like I cant obtain the 'page' parameter using the ns param because this decorator is used to retrieve parameters such as public id and its endpoint like 'user/public_id'. and i just get an error when i try to use ns.param to get the page, count etc. in this case, 'page' is a query parameter, and its endpoint is like 'user?page=1'. So, for now, I think the current approach might be okay.

2024-01-25 10:16 UTC, fatjan commented on app/main/controller/review_controller.py
> +        page = request.args.get('page', default=0, type=int)
yes, you get the value from request

But the following also works:
![Screenshot 2024-01-25 at 17 12 27](https://github.com/project-zusammen/hidden-gem-backend/assets/46950501/93b58aac-a215-4caf-9e27-831fa2f277e7)
![Screenshot 2024-01-25 at 17 14 25](https://github.com/project-zusammen/hidden-gem-backend/assets/46950501/e18bc4e2-bc56-4f9c-89a3-9d44952f04f5)

2024-01-29 23:56 UTC, fatjan requested changes
Please format your files using black and also update this branch with latest main branch to make the tests running on the pipeline.

Thank you

2024-02-06 20:59 UTC, fahmirzldi approved these changes

2024-02-14 20:31 UTC, fahmirzldi commented on app/main/model/review.py
> +            reviews = query.limit(count).offset(offset).all()
by default, what is the column used to order the data? is it by id?

2024-02-15 05:20 UTC, AchmadQiz commented on app/main/model/review.py
> +            reviews = query.limit(count).offset(offset).all()
by default is order by id, ascending

2024-03-03 00:09 UTC, fatjan submitted a review, later dismissed

2024-03-03 08:18 UTC, fatjan approved these changes

2024-03-03 08:18 UTC, merged