Feat/comment endpoint test
project-zusammen/hidden-gem-backend pull request #20
Opened 2024-01-24 11:05 UTC by fahmirzldi

Add test for comment controller, model, service

2024-01-25 06:53 UTC, fatjan commented on app/main/model/comment.py
> +        # comment = self.get_comment_by_id(public_id)
should we remove this commented line?

2024-01-25 06:53 UTC, fatjan commented on app/main/model/comment.py
> +        # comment = self.get_comment_by_id(public_id)
this one too

2024-01-25 06:54 UTC, fatjan commented on app/main/service/comment_service.py
> +        # comment.serialize()
just remove the line if it's not used

2024-01-25 12:16 UTC, fahmirzldi commented
all unnecessary comment deleted

2024-01-25 17:07 UTC, AchmadQiz commented on app/main/model/comment.py
>              return None
can you implement try catch block and add related error message? can refer to the methods in the user model

2024-01-29 01:57 UTC, fahmirzldi commented on app/main/model/comment.py
>              return None
kindly check for updated try catch

2024-01-29 23:54 UTC, fatjan requested changes
Please update as per suggestions. Thank you

2024-01-30 04:15 UTC, fahmirzldi commented on app/main/model/comment.py
> +            # comment = self.get_comment_by_id(public_id)
Done

2024-01-30 04:15 UTC, fahmirzldi commented
Updated as suggested

2024-01-30 04:58 UTC, fatjan approved these changes

2024-01-30 06:27 UTC, merged