Add tag model and review_tag model
project-zusammen/hidden-gem-backend pull request #22
Opened 2024-01-25 16:55 UTC by AchmadQiz

Add tag model and review_tag model represents the many-to-many relationship between review and tag

2024-01-28 19:17 UTC, fahmirzldi approved these changes

2024-01-29 23:44 UTC, fatjan commented on app/main/model/tag.py
> +    review_id = db.Column(db.Integer, db.ForeignKey("review.id"), nullable=False)
I think review tag table doesn't need to have a `review_id`, it is used to do a search right?

What do you think @fahmirzldi @hfzfdlh ?

2024-01-29 23:44 UTC, fatjan requested changes
Please respond to my question and adjust if you agree, thank you

2024-01-29 23:46 UTC, fatjan commented on app/main/model/tag.py
> +    review_id = db.Column(db.Integer, db.ForeignKey("review.id"), nullable=False)
I am sorry, I think I misunderstood before. This is the relationship db between review and tag, isn't it?

Could you please explain how the search will happen using this?

2024-01-29 23:47 UTC, fatjan commented on app/main/model/tag.py
> +    review_id = db.Column(db.Integer, db.ForeignKey("review.id"), nullable=False)
Does it mean each tag will have 1 to many relationship to reviews?

2024-01-30 04:21 UTC, fahmirzldi commented on app/main/model/tag.py
> +    review_id = db.Column(db.Integer, db.ForeignKey("review.id"), nullable=False)
> Does it mean each tag will have 1 to many relationship to reviews?

I assume this should be yes thats why it have this intermediate table

2024-01-30 04:23 UTC, fahmirzldi commented on app/main/model/tag.py
> +    updated_at = db.Column(db.DateTime, nullable=False)
Do we still need updated_at? I am not sure what case where we need to update a tag "definition"

2024-01-30 04:57 UTC, fatjan commented on app/main/model/tag.py
> +    updated_at = db.Column(db.DateTime, nullable=False)
good point, what do you think @AchmadQiz ?

2024-01-30 16:40 UTC, AchmadQiz commented on app/main/model/tag.py
> +    updated_at = db.Column(db.DateTime, nullable=False)
I think we don't need the updated_at column for now, and this is solely because the created_at and updated_at columns are commonly used when creating a table

2024-02-03 07:57 UTC, fatjan commented
Please fix the failed tests in the pipeline. Let me know if you need help with fixing those. Thank you

2024-02-03 16:58 UTC, AchmadQiz commented
i have fixed the tests in the pipeline

2024-02-13 19:50 UTC, fahmirzldi approved these changes
looks good

2024-02-14 13:56 UTC, fatjan approved these changes

2024-02-14 13:56 UTC, merged