Feat/create tag endpoint
project-zusammen/hidden-gem-backend pull request #23
Opened 2024-01-26 13:09 UTC by AchmadQiz

add a method to create tags based on hashtags found in the review content

2024-01-27 09:52 UTC, fatjan commented on app/main/model/review.py
> +            data = review.serialize_entire_data()
you don't need to serialize the whole data if you just need the id.

Just return review.id and serialize it only. The rest is unnecessary.

2024-01-27 09:52 UTC, fatjan requested changes
Please update per suggestion

2024-01-27 10:43 UTC, AchmadQiz commented
I have pushed the update, please kindly review it

2024-01-28 05:24 UTC, fatjan commented on tests/service/test_review_service.py
> +        print(f'\n\n\n{response}\n\n')
please remove this unnecessary print statement

2024-01-28 19:26 UTC, fahmirzldi commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
Based on [figma](https://www.figma.com/file/siksUdO6pNXFUWe3wgKLE6/User-Interface?type=design&node-id=0%3A1&mode=design&t=bzBcr2TdvbQZmUBb-1) we have tag input form. Do we change it based on the visible hashtag on content now?

2024-01-29 00:04 UTC, fatjan commented on app/main/model/review.py
> +            review = self.query.filter_by(public_id=public_id).first()
You need to filter it by `visible=True` I think

2024-01-29 00:04 UTC, fatjan commented on app/main/model/tag.py
> +            "id": self.id,
please don't return the db id in serialize

2024-01-29 00:05 UTC, fatjan requested changes
Looks good, need some minor changes only

2024-01-29 00:10 UTC, fatjan commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
This wasn't planned but I think @AchmadQiz did a good innovation by searching the content of review if any hashtags present and take it as a review tag. The downside will probably make the list of tags to be long, but let's keep it for now.

Yes, we have the tag input fields on the UI, could you please add that as well @AchmadQiz 
should be all the way from controller, service down to the model and db fields as well.
Thank you

2024-01-30 17:03 UTC, AchmadQiz commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
If these tags are extracted from the content, is the tag input field still necessary? I don't think we can add tag_id as an input because tag_id is created after the review is created. Unless these tags are not extracted from the content and created separately through input, and even then it wouldn't be tag_id but rather the name of the tag

2024-02-03 08:02 UTC, fatjan commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
Can you point out which code that says we create tag_id after creating a review?

I think we still can add a full endpoint (from controller) down to the model to create a tag. Which means we can manually add an existing tag (from db) to the new review that we create and also once we submit a review, we can extract tag from hashtag to create new tag.

I am just concerned with the way how should we extract and filter/process the extracted tag to create a new tag into our system.

For example:
```
This place is perfect for people who want to get into nature, ....

#nature #happiness #workhardplayhard #forfunpeopleonly #notforboringpeople
```

Will you take each of those tags and create a new tag out of it or will you create a new regex or something to process the extracted hashtags before we store them into the tag table?

I am saying this as someone haven't yet seen your code.

2024-02-03 08:05 UTC, fatjan commented on app/main/controller/user_controller.py
> +        page = request.args.get("page", default=None, type=int)
can we also add how many items in 1 page we want to request?

We can add a default of max. 50 items per page or 100

This will help the FE team as well, thank you

2024-02-03 08:08 UTC, fatjan commented on app/main/model/tag.py
> +                return {"id": tag.id}
why we have different format of the return?
line 38 and line 45

2024-02-03 08:13 UTC, fatjan commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
Ok, I saw your code just now:
```
def get_the_hashtag_from_content(self, content):
        try:
            return re.findall(r"\#\w+", content)
        except Exception as e:
            raise e
```

I don't think you want to add all hashtags purely into the tag table. That would be too much to store and I dnt think it will be efficient for the searching algorithm either.

Could we please improve it?

Let me know if you want to discuss further regarding how to extract and store these tags into tag model.

2024-02-03 08:15 UTC, fatjan commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
You can adjust this PR on the get user param, and then get it approved, then merge the MR

Then create a new feature branch to improve the hashtag processing if you want.

2024-02-03 08:16 UTC, fatjan requested changes
need a small change on the get user param

2024-02-03 15:22 UTC, AchmadQiz commented on app/main/model/tag.py
> +                return {"id": tag.id}
For example, when creating a tag with a name that already exists in the database, it will returns its ID. Basically this method is also used to retrieve its ID, so it doesn't have to create a new one or avoid duplicate errors.

2024-02-03 15:23 UTC, AchmadQiz commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
Well, for now I will remove it.

2024-02-03 15:31 UTC, AchmadQiz commented on app/main/service/review_service.py
> +        hashtags = review_model.get_the_hashtag_from_content(review['content'])
More precisely, I just comment it out.

2024-02-03 16:55 UTC, AchmadQiz commented
I have pushed the update, please kindly review it

2024-02-04 13:44 UTC, fatjan commented on app/main/model/tag.py
> +                return {"id": tag.id}
ok, then when this `create_tag` method is called, how do you differentiate if it creates a new one or if it calls an existing one?

2024-02-04 13:47 UTC, fatjan commented on app/main/model/tag.py
> +            "id": self.id,
please don't return the db id in serialize unless you want to remove it in the service layer before returning it as a response, but I think that would be a not worth it effort, no?

2024-02-05 09:26 UTC, AchmadQiz commented on app/main/model/tag.py
> +            "id": self.id,
i forgot, i have fixed it

2024-02-05 09:42 UTC, AchmadQiz commented on app/main/model/tag.py
> +                return {"id": tag.id}
or should i just return tag.serialize() in line 38?

2024-02-06 21:02 UTC, fahmirzldi submitted a review, later dismissed
I'm good with this update

2024-03-11 04:07 UTC, fatjan commented
Already implemented

2024-03-11 04:07 UTC, closed without merging