Feat/appeal create endpoint
project-zusammen/hidden-gem-backend pull request #28
Opened 2024-01-28 21:15 UTC by fahmirzldi

Add create endpoint for appeal + test

2024-01-28 23:57 UTC, fatjan commented on tests/model/test_appeal_model.py
> +        new_appeal = appeal_model.create_appeal(appeal_data)
I think you need to mock the `appeal_model.create_appeal(appeal_data)`

2024-01-29 00:00 UTC, fatjan requested changes
LGTM, just need a small change. Thank you

2024-01-29 00:00 UTC, fatjan commented
Don't forget to resolve the conflicts.

2024-01-29 01:25 UTC, fahmirzldi commented on tests/service/test_appeal_service.py
> +appeal_2 = {
Will keep for further use

2024-01-29 01:29 UTC, fahmirzldi commented on tests/model/test_appeal_model.py
> +        new_appeal = appeal_model.create_appeal(appeal_data)
Done

2024-01-29 01:31 UTC, fahmirzldi commented
Change request done

2024-01-29 04:39 UTC, fatjan approved these changes

2024-01-29 23:35 UTC, fatjan commented on app/main/model/appeal.py
> +# from .Report import Report
please remove these unnecessary commented lines

2024-01-29 23:40 UTC, fatjan commented on app/main/controller/appeal_controller.py
> +    @ns.expect(_appeal, validate=True)
Can you also please add the `@token_required` to your endpoint since the appeal can only be done by logged in user?

You can refer to the `user_controller` on line 47.

Or you can merge this PR (after removing the commented lines)
and then create a new feat/branch from main then implement the `token_required` on a new PR.

2024-01-29 23:40 UTC, fatjan commented on app/main/controller/appeal_controller.py
> +    @ns.expect(_appeal, validate=True)
Also make sure that appeal is done by user role `user`, not `admin`

2024-01-29 23:41 UTC, fatjan requested changes
Please adjust as per comment

2024-01-30 04:04 UTC, fahmirzldi commented
Done removing comment, will creatae new branch for implementing the token

2024-01-30 04:05 UTC, fahmirzldi commented on app/main/controller/appeal_controller.py
> +    @ns.expect(_appeal, validate=True)
Noted

2024-01-30 04:56 UTC, fatjan approved these changes

2024-01-30 05:51 UTC, merged