Feat/report update endpoint
project-zusammen/hidden-gem-backend pull request #33
Opened 2024-02-14 20:00 UTC by fahmirzldi

create report update endpoint

2024-02-20 11:53 UTC, fatjan commented on app/main/model/report.py
>      def get_all_reports(self):
do you want to implement the pagination here or will that be in the new PR?

2024-02-20 11:55 UTC, fatjan commented on tests/service/test_report_service.py
> +        data["status"] = "accepted"
I thought, the status is boolean, no? in the dto

2024-02-20 18:40 UTC, fahmirzldi commented on app/main/model/report.py
>      def get_all_reports(self):
Will be done on new PR

2024-02-20 18:49 UTC, fahmirzldi commented on tests/service/test_report_service.py
> +        data["status"] = "accepted"
I think the API contract is wrong, as mentioned here #15, the status is 

- Received
- Accepted
- Rejected

2024-02-21 06:00 UTC, fatjan commented on app/main/util/dto.py
> +    status = api.model("status", {"status": fields.Boolean(description="status")})
I think you need to update the data type on the status to `String` instead @fahmirzldi

2024-02-21 06:00 UTC, fatjan commented on tests/service/test_report_service.py
> +        data["status"] = "accepted"
You need to update the dto then. I wrote the comment on it just now.

2024-02-21 06:01 UTC, fatjan requested changes
Just a small adjustment needed, as per earlier comment.

2024-02-25 18:40 UTC, fahmirzldi commented on app/main/util/dto.py
> +    status = api.model("status", {"status": fields.Boolean(description="status")})
Done please kindly review @fatjan @AchmadQiz

2024-02-28 10:26 UTC, Achmadqizwini commented on tests/controller/test_report_controller.py
> +    "public_id": str(uuid.uuid4()),
this public_id key is duplicated

2024-03-03 00:43 UTC, fatjan approved these changes

2024-03-03 00:43 UTC, merged