Feat/user management
project-zusammen/hidden-gem-backend pull request #9
Opened 2024-01-02 16:06 UTC by AchmadQiz

2024-01-03 06:15 UTC, fatjan commented on app/main/controller/user_controller.py
> +@ns.route("/signup")
Can we make this `/user/signup` ?

2024-01-03 06:15 UTC, fatjan commented on app/main/controller/user_controller.py
> +class UserList(Resource):
I think we should rename this maybe `UserSignUp`?

2024-01-03 06:16 UTC, fatjan commented on app/main/controller/user_controller.py
> +        _updateduser = update_user(public_id, ns.payload)
this should be renamed to `updated_user`

2024-01-03 06:20 UTC, fatjan commented on app/main/model/user.py
> +            return True
why we return True here?

2024-01-03 07:10 UTC, AchmadQiz commented on app/main/model/user.py
> +            return True
I think after deletion, we don't need to return anything, so I'm returning True as a sign if the deletion was successful. the response already in user_service

2024-01-03 07:14 UTC, AchmadQiz commented on app/main/controller/user_controller.py
> +@ns.route("/signup")
i have pushed the revision

2024-01-05 12:41 UTC, fatjan commented
> _ No description provided. _

Please add some description about your PR, thanks

2024-01-05 12:43 UTC, fatjan commented on app/main/controller/user_controller.py
> +## work in progress, need authentication for this endpoint
I think other endpoints also need authentication

2024-01-05 12:43 UTC, fatjan commented on app/main/service/user_service.py
> +def updated_user_status(public_id):
this should be `update_user_status`

2024-01-05 12:44 UTC, fatjan commented on app/main/util/dto.py
> +            "username": fields.String(required=True, description="username"),
should a user be able to login using username and also email? I mean one of them should be sufficient right?

2024-01-05 14:15 UTC, AchmadQiz commented on app/main/util/dto.py
> +            "username": fields.String(required=True, description="username"),
login endpoint only use email and password, using another dto. and this on feat/user_authentication branch

2024-01-05 14:15 UTC, AchmadQiz commented on app/main/service/user_service.py
> +def updated_user_status(public_id):
done

2024-01-05 14:15 UTC, AchmadQiz commented on app/main/controller/user_controller.py
> +## work in progress, need authentication for this endpoint
the authentication is on another branch, i think after this pr is merged

2024-01-07 02:38 UTC, fatjan commented on app/main/util/dto.py
> +            "banned": fields.Boolean(required=True, description="username"),
why the field name is `banned` and the description is `username`?
I don't get it.

2024-01-07 02:40 UTC, fatjan commented on app/main/util/dto.py
> +            "username": fields.String(required=True, description="username"),
so, what's the point of having username?

Is it to be displayed on the UI?

2024-01-07 02:44 UTC, fatjan commented on tests/service/test_user_service.py
> +    updated_user,
please check your code again, I believe you updated these methods in the service. But you didn't update them in the test.

```
ImportError while importing test module '/Users/fatma/Documents/project-zusammen/hidden-gem/hidden-gem-backend/tests/service/test_user_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/service/test_user_service.py:5: in <module>
    from app.main.service.user_service import (
E   ImportError: cannot import name 'updated_user' from 'app.main.service.user_service' (/Users/fatma/Documents/project-zusammen/hidden-gem/hidden-gem-backend/app/main/service/user_service.py)
```

2024-01-07 02:44 UTC, fatjan commented on tests/service/test_user_service.py
> +    updated_user,
Please make sure to run your tests locally and ensure everything pass

2024-01-07 02:45 UTC, fatjan requested changes
Please update your tests and make sure everything pass

2024-01-09 02:43 UTC, AchmadQiz commented
i have update the unittest, please kindly review

2024-01-09 04:36 UTC, fatjan commented on tests/controller/test_user_controller.py
> +# import json
why all these are commented?

2024-01-09 04:36 UTC, fatjan requested changes
Please update your test to be not being commented

2024-01-09 04:37 UTC, fatjan commented on tests/service/test_user_service.py
> +# import uuid
Please uncomment these tests

2024-01-11 15:49 UTC, AchmadQiz commented
Sorry, It seems like I forgot to uncomment. I have pushed the update for uncomment.

2024-01-11 23:59 UTC, fatjan requested changes
Please resolve the conflicts, thank you

2024-01-12 02:43 UTC, fatjan commented on tests/service/test_user_service.py
> +        self.assertEqual(response["message"], "Successfully update status user")
It should be `user status`

2024-01-12 02:44 UTC, fatjan commented on tests/model/test_user_model.py
> +        print("\n\n\n\n\n")
please remove the print statements

2024-01-12 02:45 UTC, fatjan requested changes
please update as suggested

2024-01-12 04:27 UTC, AchmadQiz commented
I have pushed the update

2024-01-12 04:59 UTC, fatjan commented on tests/controller/test_user_controller.py
> +            "message": "Successfully update status user",
Don't you need to update this as well?

how did you run the test locally? did all pass?

2024-01-12 05:03 UTC, fatjan commented on tests/controller/test_user_controller.py
> +            "message": "Successfully update status user",
How did you update your branch with the updated main branch?

I tried running the test in your branch locally. The test failed:

```
Traceback (most recent call last):
  File "/Users/fatma/.pyenv/versions/hgem/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/flask/cli.py", line 1064, in main
    cli.main()
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/flask/cli.py", line 912, in run_command
    raise e from None
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/flask/cli.py", line 898, in run_command
    app = info.load_app()
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/flask/cli.py", line 313, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/Users/fatma/.pyenv/versions/3.9.16/envs/hgem/lib/python3.9/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/Users/fatma/Documents/project-zusammen/hidden-gem/hidden-gem-backend/app/__init__.py", line 1, in <module>
    from .main import create_app
  File "/Users/fatma/Documents/project-zusammen/hidden-gem/hidden-gem-backend/app/main/__init__.py", line 14, in <module>
    from app.main.controller.review_controller import ns as review_ns
  File "/Users/fatma/Documents/project-zusammen/hidden-gem/hidden-gem-backend/app/main/controller/review_controller.py", line 5, in <module>
    _upvote = review_dto.upvote
AttributeError: 'ReviewDto' object has no attribute 'upvote'
```

2024-01-12 05:03 UTC, fatjan commented on tests/controller/test_user_controller.py
> +            "message": "Successfully update status user",
It seems that the updated main branch from @hfzfdlh is not in your branch yet

2024-01-12 06:23 UTC, AchmadQiz commented
I have pushed the update, bismillah

2024-01-13 03:59 UTC, fatjan approved these changes

2024-01-13 04:39 UTC, merged